# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: github-welcome-flow

on:
  push:
    branches:
      - master
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 19
      uses: actions/setup-java@v4
      with:
        java-version: '19'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn clean install

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
            image: dilshan244/welcome
            tags: latest
            registry: docker.io
            dockerfile: Dockerfile
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
  deploy-to-cloud-run:
        runs-on: ubuntu-latest
        needs: build-and-push
        steps:
          - name: Authenticate with Google Cloud
            uses: google-github-actions/auth@v1
            with:
              credentials_json: ${{ secrets.GCP_CREDENTIALS }}

          - name: Set up Cloud SDK
            uses: google-github-actions/setup-gcloud@v1

          - name: Deploy to Cloud Run
            run: |
              gcloud run deploy spring-boot-app \
                --image=docker.io/dilshan244/welcome:latest \
                --platform=managed \
                --region=us-central1 \
                --allow-unauthenticated


